---
title: "Maladies cardiovasculaires"
author: "___"
date: "___"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
```


# Introduction

<!--% Écrivez une courte introduction de 2 à 4 phrases à propos de la relation entre obésité et maladies cardiovasculaires -->

<!--# Ces données sont issues d'un jeu de données public dont le lien est le suivant : <https://www.kaggle.com/sulianova/cardiovascular-disease-dataset>. Vous trouverez des informations complémentaires sur les données. -->


# Analyses

<!--% Importez les données depuis `data/cardio.rds`. -->

```{r import}

```


## Exploration des données

<!--% Comme vous le savez, il est utile de calculer des métriques qui quantifient au mieux ce que l'on étudie. Calculer donc ici l'indice de masse corporelle pour ces patients. -->

```{r imc}

```

<!--% Réalisez un graphique en boites de dispersion parallèles afin de visualiser l'imc en fonction de la présence ou de l'absence de maladie cardiocasculaire. -->

```{r imc_graph}

```

<!--% Interprétez ce graphique ci-dessous en 2 à 5 phrases. Utilisez des valeurs chiffrées pour préciser vos observations. -->


## Test d'hypothèse

<!--% Vous allez déterminer  si l'imc diffère entre les personnes atteintes de maladies cardiovasculaires ou non. Commencez par formuler précisément l'hypothèse nulle et l'hypothèse alternative ci-dessous. -->


### Conditions de validité

<!--% Discutez ensuite des conditions d'application du test choisi par rapport à vos données en 3 à 5 phrases. Peut-on utiliser ce test dans le cas présent et pourquoi ? -->


<!--% Réalisez un test d'hypothèse approprié pour répondre à la question. -->

```{r ttest}

```

<!--% Interprétez votre test en maximum 5 phrases. Interprétez votre test d'abord sur le plan statistique. Ensuite, tirez des conclusions sur le plan biologique à partir de vos résultats. -->

